-- sql/schema.sql
-- MySQL 8+ (ajuste engine/charset conforme seu servidor)

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  person_type ENUM('FISICA','JURIDICA') NOT NULL DEFAULT 'FISICA',
  cpf_cnpj VARCHAR(20) UNIQUE,
  document VARCHAR(30),
  email VARCHAR(120) UNIQUE,
  phone VARCHAR(30),
  photo_url VARCHAR(255),
  status TINYINT(1) NOT NULL DEFAULT 1,
  group_default_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS groups (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL UNIQUE,
  description VARCHAR(255),
  status TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_group (
  user_id BIGINT UNSIGNED NOT NULL,
  group_id BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (user_id, group_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS environments (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  env_type ENUM('PORTA','PORTAO','CANCELA','CATRACA','ELEVADOR','AREA') NOT NULL DEFAULT 'PORTA',
  status TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS devices (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  device_type ENUM('FACE','RFID','QRCODE','BIOMETRIA','FECHADURA','CONTROLADORA') NOT NULL,
  environment_id BIGINT UNSIGNED NULL,
  client_id BIGINT UNSIGNED NULL,
  ip VARCHAR(45),
  mac VARCHAR(17) UNIQUE,
  status TINYINT(1) NOT NULL DEFAULT 1,
  last_seen TIMESTAMP NULL DEFAULT NULL,
  fw_version VARCHAR(40),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (environment_id) REFERENCES environments(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rules (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  priority INT NOT NULL DEFAULT 0,
  status TINYINT(1) NOT NULL DEFAULT 1,
  valid_from DATETIME NULL,
  valid_to DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Targets: users or groups
CREATE TABLE IF NOT EXISTS rule_targets (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  rule_id BIGINT UNSIGNED NOT NULL,
  target_type ENUM('USER','GROUP') NOT NULL,
  target_id BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (rule_id) REFERENCES rules(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Areas allowed per rule
CREATE TABLE IF NOT EXISTS rule_areas (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  rule_id BIGINT UNSIGNED NOT NULL,
  environment_id BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (rule_id) REFERENCES rules(id) ON DELETE CASCADE,
  FOREIGN KEY (environment_id) REFERENCES environments(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Schedule (days/hours) per rule
CREATE TABLE IF NOT EXISTS rule_schedules (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  rule_id BIGINT UNSIGNED NOT NULL,
  weekday SET('MON','TUE','WED','THU','FRI','SAT','SUN') NOT NULL,
  time_start TIME NOT NULL,
  time_end TIME NOT NULL,
  FOREIGN KEY (rule_id) REFERENCES rules(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS access_logs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  occurred_at DATETIME NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  device_id BIGINT UNSIGNED NULL,
  environment_id BIGINT UNSIGNED NULL,
  result ENUM('ALLOW','DENY') NOT NULL,
  reason VARCHAR(120) NULL,
  origin ENUM('ONLINE','OFFLINE') NOT NULL DEFAULT 'ONLINE',
  snapshot_url VARCHAR(255) NULL,
  payload JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX (occurred_at),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE SET NULL,
  FOREIGN KEY (environment_id) REFERENCES environments(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS visitors (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  document VARCHAR(30),
  contact VARCHAR(80),
  host_user_id BIGINT UNSIGNED NULL,
  status TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (host_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS visitor_passes (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  visitor_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(64) NOT NULL UNIQUE,
  valid_from DATETIME NOT NULL,
  valid_to DATETIME NOT NULL,
  status TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (visitor_id) REFERENCES visitors(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- MQTT / Integrações
CREATE TABLE IF NOT EXISTS mqtt_settings (
  id TINYINT PRIMARY KEY DEFAULT 1,
  host VARCHAR(120) NOT NULL,
  port INT NOT NULL DEFAULT 1883,
  username VARCHAR(80),
  password VARCHAR(120),
  use_tls TINYINT(1) NOT NULL DEFAULT 0,
  base_topic VARCHAR(120) DEFAULT '/w/mod',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS device_topics (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  device_id BIGINT UNSIGNED NOT NULL,
  topic_cmd VARCHAR(200) NOT NULL,
  topic_status VARCHAR(200) NOT NULL,
  topic_event VARCHAR(200),
  FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Nota: Para suporte a primary_device_id e environment_devices_aux, use também os comandos em sql/setup_full.sql (se necessário).
